In [11]:
# Question 1: Arrays

import numpy

def arrays(arr):
    a = numpy.array(arr)
    lst = [i for i in a[::-1]]    
    return numpy.array(lst, float)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [22]:
# Question 2: Shape and Reshape

import numpy as np

arr = input().strip().split(' ')
array = np.array(arr, int)
print(np.reshape(array,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
# Question 3: Transpose and Flatten

import numpy as np

arr = input().strip().split(' ')
lst = []
for i in range(int(arr[0])):
    p = input().strip().split()
    lst.append(p)
    
ar = np.array(lst, int)
print(np.transpose(ar))
print(ar.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [64]:
# Question 4: Concatenate

import numpy as np

n, m, p = map(int, input().strip().split())

lst1 = [input().strip().split(' ') for i in range(n)]
lst2 = [input().strip().split(' ') for i in range(m)]
    
arr1 = np.array(lst1, int)
arr2 = np.array(lst2, int)
print(np.concatenate((arr1, arr2), axis = 0))


3 2 2
1 2
1 2
1 2
3 2
3 2
[[1 2]
 [1 2]
 [1 2]
 [3 2]
 [3 2]]


In [37]:
# Question 5: Zeros and Ones

import numpy as np

inp = input().strip().split(' ')
inp_lst = list(np.array(inp,int))

print(np.zeros(inp_lst, dtype = np.int))
print(np.ones(inp_lst, dtype = np.int))

3 2 3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [6]:
# Question 6: Eye and Identity

import numpy as np
np.set_printoptions(legacy='1.13')

n, m = map(int, input().strip().split(' '))
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [28]:
# Question 7: Array Mathematics

import numpy as np

def operation(a,b):
    print(np.add(a,b))
    print(np.subtract(a,b))
    print(np.multiply(a,b))
    print(np.floor_divide(a,b))
    print(np.mod(a,b))
    print(np.power(a,b))
    
if __name__ == '__main__':
    n, m = map(int, input().split(' '))
    a = [np.array(input().split(), int) for _ in range(n)]
    b = [np.array(input().split(), int) for _ in range(n)]
    operation(a,b)

2 4
1 2 3 4
1 2 3 4
5 6 7 8
5 6 7 8
[[ 6  8 10 12]
 [ 6  8 10 12]]
[[-4 -4 -4 -4]
 [-4 -4 -4 -4]]
[[ 5 12 21 32]
 [ 5 12 21 32]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [1 2 3 4]]
[[    1    64  2187 65536]
 [    1    64  2187 65536]]


In [29]:
# Question 8: Floor, Ceil and Rint

import numpy as np
np.set_printoptions(legacy = '1.13')

n = np.array(input().strip().split(' '), float)

print(np.floor(n))
print(np.ceil(n))
print(np.rint(n))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [30]:
# Question 9: Sum and Prod

import numpy as np

n, m = map(int, input().strip().split(' '))
inp = [np.array(input().strip().split(), int) for _ in range(n)]

print(np.prod(np.sum(inp, axis=0)))

2 2
1 2
3 4
24


In [32]:
# Question 10: Min and Max

import numpy as np

n, m = map(int, input().strip().split(' '))
inp = [np.array(input().strip().split(), int) for _ in range(n)]

print(np.max(np.min(inp, axis = 1)))

4 2
2 5
3 7
1 3
4 0
3


In [2]:
# Question 11: Mean, Var, and Std

import numpy as np

n, m = map(int, input().strip().split())
arr = [np.array(input().strip().split(), int) for _ in range(n)]

print(np.mean(arr, axis=1))
print(np.var(arr, axis=0))
print(round(np.std(arr, axis=None),11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


In [3]:
# Question 12: Dot and Cross

import numpy as np

n = int(input())
a = [np.array(input().strip().split(), int) for _ in range(n)]
b = [np.array(input().strip().split(), int) for _ in range(n)]

print(np.dot(a,b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [8]:
# Question 13: Inner and Outer

import numpy as np

a = np.array(input().strip().split(), int)
b = np.array(input().strip().split(), int)

print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [25]:
# Question 14: Polynomials

import numpy as np

inp = input().strip().split(' ')
p = np.poly1d(np.array(inp, float))
pos = int(input())

print(np.polyval(p,pos))

1.1 2 3
0
3.0


In [26]:
# Question 15: Linear Algebra

import numpy as np

n = int(input())
mat = [np.array(input().strip().split(), float) for _ in range(n)]
print(round(np.linalg.det(mat),2))

2
1.1 1.1
1.1 1.1
0.0
